### ISSUE TITLE
[feature request] An fully clean video playing experience

### ISSUE THREAD

**Issue by Avimitin** [reorx/minimal-bilibili#4]
I really love the current progress, and I am really appreciate all the work you've done now. But I think it can go one step further: a YouTube Invidious like browser plugin. Since we still need high quality playback, using the invidious approach is not ideal. But we can sacrifice a bit on privacy, but take the clean design from it:

* For the video detail page
  - Read URL before sending request to BiliBili and remove privacy tracking query parameters from it.
  - Remove the ADs and video suggestions, keep only video and comments.

**Comment by reorx** [comment]
These features are interesting; however, they require significant effort (such as exploring the DOM structure of the video page and crafting styles), necessitating a large investment of time that I cannot currently afford. I may revisit this issue in a month or two.

If you have time, I strongly encourage you to attempt to implement a demo and submit a PR. I will help you refine it in my spare time. Because you know, reviewing and optimizing is much lighter work than creating something completely new.

**Comment by Avimitin** [comment]
Sorry for bothering, but recently I found this interesting plugin implementing "almost" the same idea: https://addons.mozilla.org/en-US/firefox/addon/bewlybewly/ . But it is just enhancing the UI, w/o any further privacy customization. I mixed it with https://github.com/ClearURLs/Addon, they are working great!

**Comment by reorx** [comment]
Awesome plugin, thanks for recommendation!
